/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DetectionTaskJobData {
  uuid: string;
  cfg: DetectionTaskCfgData;
  launchedDate: string;
  finishedDate: string | null;
  status: string;
  error: string | null;
  nTotal: number;
  nProcessed: number;
  [k: string]: unknown;
}
export interface DetectionTaskCfgData {
  uuid: string;
  targetDirs: string[];
  saveDir: string;
  configs: (EmbeddedFileDetectionTaskCfgData | MaliciousDocDetectionTaskCfgData)[];
  [k: string]: unknown;
}
export interface EmbeddedFileDetectionTaskCfgData {
  maxDepth: number;
  type?: "embedded-file";
  [k: string]: unknown;
}
export interface MaliciousDocDetectionTaskCfgData {
  severityThreshold: number;
  type?: "malicious-doc";
  [k: string]: unknown;
}
