/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DetectedFileData {
  id: number;
  jobUuid: string;
  metadata: FileMetadataData;
  results: (MaliciousDocDetectionTaskResData | EmbeddedFileDetectionTaskResData)[];
  [k: string]: unknown;
}
export interface FileMetadataData {
  id: number;
  path: string;
  data: FileDataData;
  created: string;
  modified: string;
  creator: string;
  modifier: string;
  [k: string]: unknown;
}
export interface FileDataData {
  md5: string;
  size: number;
  kind: string;
  mime?: string | null;
  body?: string | null;
  is_embedded?: boolean;
  is_nested?: boolean;
  isLocallyCreated: string;
  description?: string | null;
  [k: string]: unknown;
}
export interface MaliciousDocDetectionTaskResData {
  severity: string;
  category: string;
  description: string;
  confidence: number;
  remediation: string;
  type?: "malicious-doc";
  [k: string]: unknown;
}
export interface EmbeddedFileDetectionTaskResData {
  parentId: number | null;
  childIds: number[];
  children: string[];
  type?: "embedded-file";
  [k: string]: unknown;
}
