/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EmbDetectionRunData {
  uuid: string;
  cfg: EmbDetectionConfigData;
  launchedDate: string;
  finishedDate: string | null;
  status: string;
  error: string | null;
  nTotal: number;
  nProcessed: number;

  [k: string]: unknown;
}

export interface EmbDetectionConfigData {
  uuid: string;
  targetDirs: string[];
  saveDirs: string;
  maxDepth: number;

  [k: string]: unknown;
}
