/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FileMetadataData {
  id: number;
  path: string;
  data: FileDataData;
  created: string;
  modified: string;
  creator: string;
  modifier: string;
  [k: string]: unknown;
}
export interface FileDataData {
  md5: string;
  size: number;
  kind: string;
  mime?: string | null;
  body?: string | null;
  [k: string]: unknown;
}
