/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FileDataData {
  md5: string;
  size: number;
  kind: string;
  mime?: string | null;
  body?: string | null;
  is_embedded?: boolean;
  is_nested?: boolean;
  isLocallyCreated: string;
  description?: string | null;
  [k: string]: unknown;
}
