/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MaliciousDocDetectionTaskResData {
  severity: string;
  category: string;
  description: string;
  confidence: number;
  remediation: string;
  type?: "malicious-doc";

  [k: string]: unknown;
}
